// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services/ClientService.proto
#ifndef GRPC_Services_2fClientService_2eproto__INCLUDED
#define GRPC_Services_2fClientService_2eproto__INCLUDED

#include "Services/ClientService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace GrpcApiPractice {

class ClientService final {
 public:
  static constexpr char const* service_full_name() {
    return "GrpcApiPractice.ClientService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::GrpcApiPractice::ServiceStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>> AsyncCreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>>(AsyncCreateClientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>> PrepareAsyncCreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>>(PrepareAsyncCreateClientRaw(context, request, cq));
    }
    virtual ::grpc::Status ListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcApiPractice::ListClientResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>> AsyncListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>>(AsyncListClientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>> PrepareAsyncListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>>(PrepareAsyncListClientRaw(context, request, cq));
    }
    virtual ::grpc::Status ListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::GrpcApiPractice::ListClientResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>> AsyncListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>>(AsyncListClientByIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>> PrepareAsyncListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>>(PrepareAsyncListClientByIdRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client* request, ::GrpcApiPractice::ServiceStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client* request, ::GrpcApiPractice::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListClientResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListClientResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest* request, ::GrpcApiPractice::ListClientResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest* request, ::GrpcApiPractice::ListClientResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>* AsyncCreateClientRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>* PrepareAsyncCreateClientRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>* AsyncListClientRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>* PrepareAsyncListClientRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>* AsyncListClientByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListClientResponse>* PrepareAsyncListClientByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::GrpcApiPractice::ServiceStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>> AsyncCreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>>(AsyncCreateClientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>> PrepareAsyncCreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>>(PrepareAsyncCreateClientRaw(context, request, cq));
    }
    ::grpc::Status ListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcApiPractice::ListClientResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>> AsyncListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>>(AsyncListClientRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>> PrepareAsyncListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>>(PrepareAsyncListClientRaw(context, request, cq));
    }
    ::grpc::Status ListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::GrpcApiPractice::ListClientResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>> AsyncListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>>(AsyncListClientByIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>> PrepareAsyncListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>>(PrepareAsyncListClientByIdRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client* request, ::GrpcApiPractice::ServiceStatus* response, std::function<void(::grpc::Status)>) override;
      void CreateClient(::grpc::ClientContext* context, const ::GrpcApiPractice::Client* request, ::GrpcApiPractice::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListClientResponse* response, std::function<void(::grpc::Status)>) override;
      void ListClient(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListClientResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest* request, ::GrpcApiPractice::ListClientResponse* response, std::function<void(::grpc::Status)>) override;
      void ListClientById(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest* request, ::GrpcApiPractice::ListClientResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>* AsyncCreateClientRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>* PrepareAsyncCreateClientRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Client& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>* AsyncListClientRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>* PrepareAsyncListClientRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>* AsyncListClientByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListClientResponse>* PrepareAsyncListClientByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::ClientByIdRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateClient_;
    const ::grpc::internal::RpcMethod rpcmethod_ListClient_;
    const ::grpc::internal::RpcMethod rpcmethod_ListClientById_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateClient(::grpc::ServerContext* context, const ::GrpcApiPractice::Client* request, ::GrpcApiPractice::ServiceStatus* response);
    virtual ::grpc::Status ListClient(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListClientResponse* response);
    virtual ::grpc::Status ListClientById(::grpc::ServerContext* context, const ::GrpcApiPractice::ClientByIdRequest* request, ::GrpcApiPractice::ListClientResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateClient() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateClient(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateClient(::grpc::ServerContext* context, ::GrpcApiPractice::Client* request, ::grpc::ServerAsyncResponseWriter< ::GrpcApiPractice::ServiceStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListClient() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClient(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListClient(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::GrpcApiPractice::ListClientResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListClientById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListClientById() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListClientById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClientById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListClientById(::grpc::ServerContext* context, ::GrpcApiPractice::ClientByIdRequest* request, ::grpc::ServerAsyncResponseWriter< ::GrpcApiPractice::ListClientResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateClient<WithAsyncMethod_ListClient<WithAsyncMethod_ListClientById<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateClient() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::Client, ::GrpcApiPractice::ServiceStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GrpcApiPractice::Client* request, ::GrpcApiPractice::ServiceStatus* response) { return this->CreateClient(context, request, response); }));}
    void SetMessageAllocatorFor_CreateClient(
        ::grpc::MessageAllocator< ::GrpcApiPractice::Client, ::GrpcApiPractice::ServiceStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::Client, ::GrpcApiPractice::ServiceStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateClient(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateClient(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListClient() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::GrpcApiPractice::ListClientResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListClientResponse* response) { return this->ListClient(context, request, response); }));}
    void SetMessageAllocatorFor_ListClient(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::GrpcApiPractice::ListClientResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::GrpcApiPractice::ListClientResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClient(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListClient(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListClientById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListClientById() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::ClientByIdRequest, ::GrpcApiPractice::ListClientResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GrpcApiPractice::ClientByIdRequest* request, ::GrpcApiPractice::ListClientResponse* response) { return this->ListClientById(context, request, response); }));}
    void SetMessageAllocatorFor_ListClientById(
        ::grpc::MessageAllocator< ::GrpcApiPractice::ClientByIdRequest, ::GrpcApiPractice::ListClientResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::ClientByIdRequest, ::GrpcApiPractice::ListClientResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListClientById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClientById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListClientById(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateClient<WithCallbackMethod_ListClient<WithCallbackMethod_ListClientById<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateClient() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateClient(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListClient() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClient(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListClientById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListClientById() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListClientById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClientById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateClient() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateClient(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateClient(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListClient() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClient(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListClient(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListClientById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListClientById() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListClientById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClientById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListClientById(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateClient() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateClient(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateClient(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateClient(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListClient() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListClient(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClient(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListClient(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListClientById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListClientById() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListClientById(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListClientById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListClientById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListClientById(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateClient() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcApiPractice::Client, ::GrpcApiPractice::ServiceStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcApiPractice::Client, ::GrpcApiPractice::ServiceStatus>* streamer) {
                       return this->StreamedCreateClient(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateClient(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Client* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateClient(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcApiPractice::Client,::GrpcApiPractice::ServiceStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListClient : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListClient() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::GrpcApiPractice::ListClientResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::GrpcApiPractice::ListClientResponse>* streamer) {
                       return this->StreamedListClient(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListClient() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListClient(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListClient(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::GrpcApiPractice::ListClientResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListClientById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListClientById() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcApiPractice::ClientByIdRequest, ::GrpcApiPractice::ListClientResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcApiPractice::ClientByIdRequest, ::GrpcApiPractice::ListClientResponse>* streamer) {
                       return this->StreamedListClientById(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListClientById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListClientById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::ClientByIdRequest* /*request*/, ::GrpcApiPractice::ListClientResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListClientById(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcApiPractice::ClientByIdRequest,::GrpcApiPractice::ListClientResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateClient<WithStreamedUnaryMethod_ListClient<WithStreamedUnaryMethod_ListClientById<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateClient<WithStreamedUnaryMethod_ListClient<WithStreamedUnaryMethod_ListClientById<Service > > > StreamedService;
};

}  // namespace GrpcApiPractice


#endif  // GRPC_Services_2fClientService_2eproto__INCLUDED
