// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Services/InvoiceService.proto

#include "Services/InvoiceService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace GrpcApiPractice {
PROTOBUF_CONSTEXPR InvoiceByIdRequest::InvoiceByIdRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.invoice_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InvoiceByIdRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvoiceByIdRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvoiceByIdRequestDefaultTypeInternal() {}
  union {
    InvoiceByIdRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvoiceByIdRequestDefaultTypeInternal _InvoiceByIdRequest_default_instance_;
PROTOBUF_CONSTEXPR ListInvoiceResponse::ListInvoiceResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.invoice_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ListInvoiceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListInvoiceResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListInvoiceResponseDefaultTypeInternal() {}
  union {
    ListInvoiceResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListInvoiceResponseDefaultTypeInternal _ListInvoiceResponse_default_instance_;
}  // namespace GrpcApiPractice
static ::_pb::Metadata file_level_metadata_Services_2fInvoiceService_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Services_2fInvoiceService_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Services_2fInvoiceService_2eproto = nullptr;

const uint32_t TableStruct_Services_2fInvoiceService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceByIdRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceByIdRequest, _impl_.invoice_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::ListInvoiceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::ListInvoiceResponse, _impl_.invoice_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::GrpcApiPractice::InvoiceByIdRequest)},
  { 7, -1, -1, sizeof(::GrpcApiPractice::ListInvoiceResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::GrpcApiPractice::_InvoiceByIdRequest_default_instance_._instance,
  &::GrpcApiPractice::_ListInvoiceResponse_default_instance_._instance,
};

const char descriptor_table_protodef_Services_2fInvoiceService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035Services/InvoiceService.proto\022\017GrpcApi"
  "Practice\032\024Models/Invoice.proto\032\032Models/S"
  "erviceStatus.proto\032\033google/protobuf/empt"
  "y.proto\"(\n\022InvoiceByIdRequest\022\022\n\ninvoice"
  "_id\030\001 \001(\003\"@\n\023ListInvoiceResponse\022)\n\007invo"
  "ice\030\001 \003(\0132\030.GrpcApiPractice.Invoice2\214\002\n\016"
  "InvoiceService\022K\n\rCreateInvoice\022\030.GrpcAp"
  "iPractice.Invoice\032\036.GrpcApiPractice.Serv"
  "iceStatus\"\000\022M\n\013ListInvoice\022\026.google.prot"
  "obuf.Empty\032$.GrpcApiPractice.ListInvoice"
  "Response\"\000\022^\n\017ListInvoiceById\022#.GrpcApiP"
  "ractice.InvoiceByIdRequest\032$.GrpcApiPrac"
  "tice.ListInvoiceResponse\"\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Services_2fInvoiceService_2eproto_deps[3] = {
  &::descriptor_table_Models_2fInvoice_2eproto,
  &::descriptor_table_Models_2fServiceStatus_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_Services_2fInvoiceService_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Services_2fInvoiceService_2eproto = {
    false, false, 514, descriptor_table_protodef_Services_2fInvoiceService_2eproto,
    "Services/InvoiceService.proto",
    &descriptor_table_Services_2fInvoiceService_2eproto_once, descriptor_table_Services_2fInvoiceService_2eproto_deps, 3, 2,
    schemas, file_default_instances, TableStruct_Services_2fInvoiceService_2eproto::offsets,
    file_level_metadata_Services_2fInvoiceService_2eproto, file_level_enum_descriptors_Services_2fInvoiceService_2eproto,
    file_level_service_descriptors_Services_2fInvoiceService_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Services_2fInvoiceService_2eproto_getter() {
  return &descriptor_table_Services_2fInvoiceService_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Services_2fInvoiceService_2eproto(&descriptor_table_Services_2fInvoiceService_2eproto);
namespace GrpcApiPractice {

// ===================================================================

class InvoiceByIdRequest::_Internal {
 public:
};

InvoiceByIdRequest::InvoiceByIdRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcApiPractice.InvoiceByIdRequest)
}
InvoiceByIdRequest::InvoiceByIdRequest(const InvoiceByIdRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InvoiceByIdRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.invoice_id_ = from._impl_.invoice_id_;
  // @@protoc_insertion_point(copy_constructor:GrpcApiPractice.InvoiceByIdRequest)
}

inline void InvoiceByIdRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InvoiceByIdRequest::~InvoiceByIdRequest() {
  // @@protoc_insertion_point(destructor:GrpcApiPractice.InvoiceByIdRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InvoiceByIdRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InvoiceByIdRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InvoiceByIdRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcApiPractice.InvoiceByIdRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.invoice_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InvoiceByIdRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 invoice_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.invoice_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InvoiceByIdRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcApiPractice.InvoiceByIdRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 invoice_id = 1;
  if (this->_internal_invoice_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_invoice_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcApiPractice.InvoiceByIdRequest)
  return target;
}

size_t InvoiceByIdRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcApiPractice.InvoiceByIdRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 invoice_id = 1;
  if (this->_internal_invoice_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_invoice_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InvoiceByIdRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InvoiceByIdRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InvoiceByIdRequest::GetClassData() const { return &_class_data_; }


void InvoiceByIdRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InvoiceByIdRequest*>(&to_msg);
  auto& from = static_cast<const InvoiceByIdRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcApiPractice.InvoiceByIdRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_invoice_id() != 0) {
    _this->_internal_set_invoice_id(from._internal_invoice_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InvoiceByIdRequest::CopyFrom(const InvoiceByIdRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcApiPractice.InvoiceByIdRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InvoiceByIdRequest::IsInitialized() const {
  return true;
}

void InvoiceByIdRequest::InternalSwap(InvoiceByIdRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.invoice_id_, other->_impl_.invoice_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InvoiceByIdRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Services_2fInvoiceService_2eproto_getter, &descriptor_table_Services_2fInvoiceService_2eproto_once,
      file_level_metadata_Services_2fInvoiceService_2eproto[0]);
}

// ===================================================================

class ListInvoiceResponse::_Internal {
 public:
};

void ListInvoiceResponse::clear_invoice() {
  _impl_.invoice_.Clear();
}
ListInvoiceResponse::ListInvoiceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcApiPractice.ListInvoiceResponse)
}
ListInvoiceResponse::ListInvoiceResponse(const ListInvoiceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ListInvoiceResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_){from._impl_.invoice_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:GrpcApiPractice.ListInvoiceResponse)
}

inline void ListInvoiceResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ListInvoiceResponse::~ListInvoiceResponse() {
  // @@protoc_insertion_point(destructor:GrpcApiPractice.ListInvoiceResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ListInvoiceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.invoice_.~RepeatedPtrField();
}

void ListInvoiceResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ListInvoiceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcApiPractice.ListInvoiceResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.invoice_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ListInvoiceResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .GrpcApiPractice.Invoice invoice = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_invoice(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ListInvoiceResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcApiPractice.ListInvoiceResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .GrpcApiPractice.Invoice invoice = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_invoice_size()); i < n; i++) {
    const auto& repfield = this->_internal_invoice(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcApiPractice.ListInvoiceResponse)
  return target;
}

size_t ListInvoiceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcApiPractice.ListInvoiceResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GrpcApiPractice.Invoice invoice = 1;
  total_size += 1UL * this->_internal_invoice_size();
  for (const auto& msg : this->_impl_.invoice_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListInvoiceResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ListInvoiceResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListInvoiceResponse::GetClassData() const { return &_class_data_; }


void ListInvoiceResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ListInvoiceResponse*>(&to_msg);
  auto& from = static_cast<const ListInvoiceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcApiPractice.ListInvoiceResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.invoice_.MergeFrom(from._impl_.invoice_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ListInvoiceResponse::CopyFrom(const ListInvoiceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcApiPractice.ListInvoiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListInvoiceResponse::IsInitialized() const {
  return true;
}

void ListInvoiceResponse::InternalSwap(ListInvoiceResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.invoice_.InternalSwap(&other->_impl_.invoice_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ListInvoiceResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Services_2fInvoiceService_2eproto_getter, &descriptor_table_Services_2fInvoiceService_2eproto_once,
      file_level_metadata_Services_2fInvoiceService_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace GrpcApiPractice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GrpcApiPractice::InvoiceByIdRequest*
Arena::CreateMaybeMessage< ::GrpcApiPractice::InvoiceByIdRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcApiPractice::InvoiceByIdRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::GrpcApiPractice::ListInvoiceResponse*
Arena::CreateMaybeMessage< ::GrpcApiPractice::ListInvoiceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcApiPractice::ListInvoiceResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
