// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services/InvoiceService.proto
#ifndef GRPC_Services_2fInvoiceService_2eproto__INCLUDED
#define GRPC_Services_2fInvoiceService_2eproto__INCLUDED

#include "Services/InvoiceService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace GrpcApiPractice {

class InvoiceService final {
 public:
  static constexpr char const* service_full_name() {
    return "GrpcApiPractice.InvoiceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::GrpcApiPractice::ServiceStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>> AsyncCreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>>(AsyncCreateInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>> PrepareAsyncCreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>>(PrepareAsyncCreateInvoiceRaw(context, request, cq));
    }
    virtual ::grpc::Status ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcApiPractice::ListInvoiceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>> AsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>>(AsyncListInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>> PrepareAsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>>(PrepareAsyncListInvoiceRaw(context, request, cq));
    }
    virtual ::grpc::Status ListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::GrpcApiPractice::ListInvoiceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>> AsyncListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>>(AsyncListInvoiceByIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>> PrepareAsyncListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>>(PrepareAsyncListInvoiceByIdRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice* request, ::GrpcApiPractice::ServiceStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice* request, ::GrpcApiPractice::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListInvoiceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest* request, ::GrpcApiPractice::ListInvoiceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest* request, ::GrpcApiPractice::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>* AsyncCreateInvoiceRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ServiceStatus>* PrepareAsyncCreateInvoiceRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>* AsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>* PrepareAsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>* AsyncListInvoiceByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcApiPractice::ListInvoiceResponse>* PrepareAsyncListInvoiceByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::GrpcApiPractice::ServiceStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>> AsyncCreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>>(AsyncCreateInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>> PrepareAsyncCreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>>(PrepareAsyncCreateInvoiceRaw(context, request, cq));
    }
    ::grpc::Status ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcApiPractice::ListInvoiceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>> AsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>>(AsyncListInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>> PrepareAsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>>(PrepareAsyncListInvoiceRaw(context, request, cq));
    }
    ::grpc::Status ListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::GrpcApiPractice::ListInvoiceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>> AsyncListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>>(AsyncListInvoiceByIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>> PrepareAsyncListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>>(PrepareAsyncListInvoiceByIdRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice* request, ::GrpcApiPractice::ServiceStatus* response, std::function<void(::grpc::Status)>) override;
      void CreateInvoice(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice* request, ::GrpcApiPractice::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListInvoiceResponse* response, std::function<void(::grpc::Status)>) override;
      void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest* request, ::GrpcApiPractice::ListInvoiceResponse* response, std::function<void(::grpc::Status)>) override;
      void ListInvoiceById(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest* request, ::GrpcApiPractice::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>* AsyncCreateInvoiceRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ServiceStatus>* PrepareAsyncCreateInvoiceRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::Invoice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>* AsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>* PrepareAsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>* AsyncListInvoiceByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcApiPractice::ListInvoiceResponse>* PrepareAsyncListInvoiceByIdRaw(::grpc::ClientContext* context, const ::GrpcApiPractice::InvoiceByIdRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateInvoice_;
    const ::grpc::internal::RpcMethod rpcmethod_ListInvoice_;
    const ::grpc::internal::RpcMethod rpcmethod_ListInvoiceById_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateInvoice(::grpc::ServerContext* context, const ::GrpcApiPractice::Invoice* request, ::GrpcApiPractice::ServiceStatus* response);
    virtual ::grpc::Status ListInvoice(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListInvoiceResponse* response);
    virtual ::grpc::Status ListInvoiceById(::grpc::ServerContext* context, const ::GrpcApiPractice::InvoiceByIdRequest* request, ::GrpcApiPractice::ListInvoiceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateInvoice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoice(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateInvoice(::grpc::ServerContext* context, ::GrpcApiPractice::Invoice* request, ::grpc::ServerAsyncResponseWriter< ::GrpcApiPractice::ServiceStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListInvoice() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoice(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::GrpcApiPractice::ListInvoiceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListInvoiceById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListInvoiceById() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListInvoiceById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoiceById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoiceById(::grpc::ServerContext* context, ::GrpcApiPractice::InvoiceByIdRequest* request, ::grpc::ServerAsyncResponseWriter< ::GrpcApiPractice::ListInvoiceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateInvoice<WithAsyncMethod_ListInvoice<WithAsyncMethod_ListInvoiceById<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateInvoice() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::Invoice, ::GrpcApiPractice::ServiceStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GrpcApiPractice::Invoice* request, ::GrpcApiPractice::ServiceStatus* response) { return this->CreateInvoice(context, request, response); }));}
    void SetMessageAllocatorFor_CreateInvoice(
        ::grpc::MessageAllocator< ::GrpcApiPractice::Invoice, ::GrpcApiPractice::ServiceStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::Invoice, ::GrpcApiPractice::ServiceStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoice(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListInvoice() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::GrpcApiPractice::ListInvoiceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::GrpcApiPractice::ListInvoiceResponse* response) { return this->ListInvoice(context, request, response); }));}
    void SetMessageAllocatorFor_ListInvoice(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::GrpcApiPractice::ListInvoiceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::GrpcApiPractice::ListInvoiceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListInvoiceById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListInvoiceById() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::InvoiceByIdRequest, ::GrpcApiPractice::ListInvoiceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GrpcApiPractice::InvoiceByIdRequest* request, ::GrpcApiPractice::ListInvoiceResponse* response) { return this->ListInvoiceById(context, request, response); }));}
    void SetMessageAllocatorFor_ListInvoiceById(
        ::grpc::MessageAllocator< ::GrpcApiPractice::InvoiceByIdRequest, ::GrpcApiPractice::ListInvoiceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcApiPractice::InvoiceByIdRequest, ::GrpcApiPractice::ListInvoiceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListInvoiceById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoiceById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoiceById(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateInvoice<WithCallbackMethod_ListInvoice<WithCallbackMethod_ListInvoiceById<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateInvoice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoice(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListInvoice() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListInvoiceById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListInvoiceById() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListInvoiceById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoiceById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateInvoice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoice(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateInvoice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListInvoice() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListInvoiceById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListInvoiceById() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListInvoiceById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoiceById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoiceById(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateInvoice() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateInvoice(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateInvoice(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListInvoice() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListInvoice(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListInvoiceById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListInvoiceById() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListInvoiceById(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListInvoiceById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoiceById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoiceById(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateInvoice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcApiPractice::Invoice, ::GrpcApiPractice::ServiceStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcApiPractice::Invoice, ::GrpcApiPractice::ServiceStatus>* streamer) {
                       return this->StreamedCreateInvoice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateInvoice(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::Invoice* /*request*/, ::GrpcApiPractice::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateInvoice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcApiPractice::Invoice,::GrpcApiPractice::ServiceStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListInvoice() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::GrpcApiPractice::ListInvoiceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::GrpcApiPractice::ListInvoiceResponse>* streamer) {
                       return this->StreamedListInvoice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListInvoice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::GrpcApiPractice::ListInvoiceResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListInvoiceById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListInvoiceById() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcApiPractice::InvoiceByIdRequest, ::GrpcApiPractice::ListInvoiceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcApiPractice::InvoiceByIdRequest, ::GrpcApiPractice::ListInvoiceResponse>* streamer) {
                       return this->StreamedListInvoiceById(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListInvoiceById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListInvoiceById(::grpc::ServerContext* /*context*/, const ::GrpcApiPractice::InvoiceByIdRequest* /*request*/, ::GrpcApiPractice::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListInvoiceById(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcApiPractice::InvoiceByIdRequest,::GrpcApiPractice::ListInvoiceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateInvoice<WithStreamedUnaryMethod_ListInvoice<WithStreamedUnaryMethod_ListInvoiceById<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateInvoice<WithStreamedUnaryMethod_ListInvoice<WithStreamedUnaryMethod_ListInvoiceById<Service > > > StreamedService;
};

}  // namespace GrpcApiPractice


#endif  // GRPC_Services_2fInvoiceService_2eproto__INCLUDED
