// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models/Invoice.proto

#include "Models/Invoice.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace GrpcApiPractice {
PROTOBUF_CONSTEXPR Invoice::Invoice(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.invoice_details_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.client_)*/nullptr
  , /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InvoiceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvoiceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvoiceDefaultTypeInternal() {}
  union {
    Invoice _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvoiceDefaultTypeInternal _Invoice_default_instance_;
}  // namespace GrpcApiPractice
static ::_pb::Metadata file_level_metadata_Models_2fInvoice_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Models_2fInvoice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Models_2fInvoice_2eproto = nullptr;

const uint32_t TableStruct_Models_2fInvoice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::Invoice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::Invoice, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::Invoice, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::Invoice, _impl_.address_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::Invoice, _impl_.invoice_details_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::Invoice, _impl_.client_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::GrpcApiPractice::Invoice)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::GrpcApiPractice::_Invoice_default_instance_._instance,
};

const char descriptor_table_protodef_Models_2fInvoice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024Models/Invoice.proto\022\017GrpcApiPractice\032"
  "\023Models/Client.proto\032\033Models/InvoiceDeta"
  "ils.proto\"\227\001\n\007Invoice\022\n\n\002id\030\001 \001(\004\022\014\n\004nam"
  "e\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\0228\n\017invoice_deta"
  "ils\030\004 \003(\0132\037.GrpcApiPractice.InvoiceDetai"
  "ls\022\'\n\006client\030\005 \001(\0132\027.GrpcApiPractice.Cli"
  "entb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Models_2fInvoice_2eproto_deps[2] = {
  &::descriptor_table_Models_2fClient_2eproto,
  &::descriptor_table_Models_2fInvoiceDetails_2eproto,
};
static ::_pbi::once_flag descriptor_table_Models_2fInvoice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Models_2fInvoice_2eproto = {
    false, false, 251, descriptor_table_protodef_Models_2fInvoice_2eproto,
    "Models/Invoice.proto",
    &descriptor_table_Models_2fInvoice_2eproto_once, descriptor_table_Models_2fInvoice_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_Models_2fInvoice_2eproto::offsets,
    file_level_metadata_Models_2fInvoice_2eproto, file_level_enum_descriptors_Models_2fInvoice_2eproto,
    file_level_service_descriptors_Models_2fInvoice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Models_2fInvoice_2eproto_getter() {
  return &descriptor_table_Models_2fInvoice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Models_2fInvoice_2eproto(&descriptor_table_Models_2fInvoice_2eproto);
namespace GrpcApiPractice {

// ===================================================================

class Invoice::_Internal {
 public:
  static const ::GrpcApiPractice::Client& client(const Invoice* msg);
};

const ::GrpcApiPractice::Client&
Invoice::_Internal::client(const Invoice* msg) {
  return *msg->_impl_.client_;
}
void Invoice::clear_invoice_details() {
  _impl_.invoice_details_.Clear();
}
void Invoice::clear_client() {
  if (GetArenaForAllocation() == nullptr && _impl_.client_ != nullptr) {
    delete _impl_.client_;
  }
  _impl_.client_ = nullptr;
}
Invoice::Invoice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcApiPractice.Invoice)
}
Invoice::Invoice(const Invoice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Invoice* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_details_){from._impl_.invoice_details_}
    , decltype(_impl_.name_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.client_){nullptr}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_address().empty()) {
    _this->_impl_.address_.Set(from._internal_address(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_client()) {
    _this->_impl_.client_ = new ::GrpcApiPractice::Client(*from._impl_.client_);
  }
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:GrpcApiPractice.Invoice)
}

inline void Invoice::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_details_){arena}
    , decltype(_impl_.name_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.client_){nullptr}
    , decltype(_impl_.id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Invoice::~Invoice() {
  // @@protoc_insertion_point(destructor:GrpcApiPractice.Invoice)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Invoice::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.invoice_details_.~RepeatedPtrField();
  _impl_.name_.Destroy();
  _impl_.address_.Destroy();
  if (this != internal_default_instance()) delete _impl_.client_;
}

void Invoice::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Invoice::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcApiPractice.Invoice)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.invoice_details_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.address_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.client_ != nullptr) {
    delete _impl_.client_;
  }
  _impl_.client_ = nullptr;
  _impl_.id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Invoice::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GrpcApiPractice.Invoice.name"));
        } else
          goto handle_unusual;
        continue;
      // string address = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GrpcApiPractice.Invoice.address"));
        } else
          goto handle_unusual;
        continue;
      // repeated .GrpcApiPractice.InvoiceDetails invoice_details = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_invoice_details(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .GrpcApiPractice.Client client = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_client(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Invoice::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcApiPractice.Invoice)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GrpcApiPractice.Invoice.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // string address = 3;
  if (!this->_internal_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GrpcApiPractice.Invoice.address");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_address(), target);
  }

  // repeated .GrpcApiPractice.InvoiceDetails invoice_details = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_invoice_details_size()); i < n; i++) {
    const auto& repfield = this->_internal_invoice_details(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .GrpcApiPractice.Client client = 5;
  if (this->_internal_has_client()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::client(this),
        _Internal::client(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcApiPractice.Invoice)
  return target;
}

size_t Invoice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcApiPractice.Invoice)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GrpcApiPractice.InvoiceDetails invoice_details = 4;
  total_size += 1UL * this->_internal_invoice_details_size();
  for (const auto& msg : this->_impl_.invoice_details_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string address = 3;
  if (!this->_internal_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  // .GrpcApiPractice.Client client = 5;
  if (this->_internal_has_client()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.client_);
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Invoice::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Invoice::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Invoice::GetClassData() const { return &_class_data_; }


void Invoice::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Invoice*>(&to_msg);
  auto& from = static_cast<const Invoice&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcApiPractice.Invoice)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.invoice_details_.MergeFrom(from._impl_.invoice_details_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_has_client()) {
    _this->_internal_mutable_client()->::GrpcApiPractice::Client::MergeFrom(
        from._internal_client());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Invoice::CopyFrom(const Invoice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcApiPractice.Invoice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Invoice::IsInitialized() const {
  return true;
}

void Invoice::InternalSwap(Invoice* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.invoice_details_.InternalSwap(&other->_impl_.invoice_details_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.address_, lhs_arena,
      &other->_impl_.address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Invoice, _impl_.id_)
      + sizeof(Invoice::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Invoice, _impl_.client_)>(
          reinterpret_cast<char*>(&_impl_.client_),
          reinterpret_cast<char*>(&other->_impl_.client_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Invoice::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Models_2fInvoice_2eproto_getter, &descriptor_table_Models_2fInvoice_2eproto_once,
      file_level_metadata_Models_2fInvoice_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace GrpcApiPractice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GrpcApiPractice::Invoice*
Arena::CreateMaybeMessage< ::GrpcApiPractice::Invoice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcApiPractice::Invoice >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
