// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models/InvoiceDetails.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Models_2fInvoiceDetails_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Models_2fInvoiceDetails_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Models/Product.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Models_2fInvoiceDetails_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Models_2fInvoiceDetails_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Models_2fInvoiceDetails_2eproto;
namespace GrpcApiPractice {
class InvoiceDetails;
struct InvoiceDetailsDefaultTypeInternal;
extern InvoiceDetailsDefaultTypeInternal _InvoiceDetails_default_instance_;
}  // namespace GrpcApiPractice
PROTOBUF_NAMESPACE_OPEN
template<> ::GrpcApiPractice::InvoiceDetails* Arena::CreateMaybeMessage<::GrpcApiPractice::InvoiceDetails>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GrpcApiPractice {

// ===================================================================

class InvoiceDetails final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GrpcApiPractice.InvoiceDetails) */ {
 public:
  inline InvoiceDetails() : InvoiceDetails(nullptr) {}
  ~InvoiceDetails() override;
  explicit PROTOBUF_CONSTEXPR InvoiceDetails(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InvoiceDetails(const InvoiceDetails& from);
  InvoiceDetails(InvoiceDetails&& from) noexcept
    : InvoiceDetails() {
    *this = ::std::move(from);
  }

  inline InvoiceDetails& operator=(const InvoiceDetails& from) {
    CopyFrom(from);
    return *this;
  }
  inline InvoiceDetails& operator=(InvoiceDetails&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InvoiceDetails& default_instance() {
    return *internal_default_instance();
  }
  static inline const InvoiceDetails* internal_default_instance() {
    return reinterpret_cast<const InvoiceDetails*>(
               &_InvoiceDetails_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InvoiceDetails& a, InvoiceDetails& b) {
    a.Swap(&b);
  }
  inline void Swap(InvoiceDetails* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InvoiceDetails* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InvoiceDetails* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InvoiceDetails>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InvoiceDetails& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InvoiceDetails& from) {
    InvoiceDetails::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InvoiceDetails* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GrpcApiPractice.InvoiceDetails";
  }
  protected:
  explicit InvoiceDetails(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProductFieldNumber = 1,
    kDeductionFieldNumber = 2,
    kQuantityFieldNumber = 3,
    kTotalFieldNumber = 4,
  };
  // .GrpcApiPractice.Product product = 1;
  bool has_product() const;
  private:
  bool _internal_has_product() const;
  public:
  void clear_product();
  const ::GrpcApiPractice::Product& product() const;
  PROTOBUF_NODISCARD ::GrpcApiPractice::Product* release_product();
  ::GrpcApiPractice::Product* mutable_product();
  void set_allocated_product(::GrpcApiPractice::Product* product);
  private:
  const ::GrpcApiPractice::Product& _internal_product() const;
  ::GrpcApiPractice::Product* _internal_mutable_product();
  public:
  void unsafe_arena_set_allocated_product(
      ::GrpcApiPractice::Product* product);
  ::GrpcApiPractice::Product* unsafe_arena_release_product();

  // double deduction = 2;
  void clear_deduction();
  double deduction() const;
  void set_deduction(double value);
  private:
  double _internal_deduction() const;
  void _internal_set_deduction(double value);
  public:

  // int64 quantity = 3;
  void clear_quantity();
  int64_t quantity() const;
  void set_quantity(int64_t value);
  private:
  int64_t _internal_quantity() const;
  void _internal_set_quantity(int64_t value);
  public:

  // int64 total = 4;
  void clear_total();
  int64_t total() const;
  void set_total(int64_t value);
  private:
  int64_t _internal_total() const;
  void _internal_set_total(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GrpcApiPractice.InvoiceDetails)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::GrpcApiPractice::Product* product_;
    double deduction_;
    int64_t quantity_;
    int64_t total_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Models_2fInvoiceDetails_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InvoiceDetails

// .GrpcApiPractice.Product product = 1;
inline bool InvoiceDetails::_internal_has_product() const {
  return this != internal_default_instance() && _impl_.product_ != nullptr;
}
inline bool InvoiceDetails::has_product() const {
  return _internal_has_product();
}
inline const ::GrpcApiPractice::Product& InvoiceDetails::_internal_product() const {
  const ::GrpcApiPractice::Product* p = _impl_.product_;
  return p != nullptr ? *p : reinterpret_cast<const ::GrpcApiPractice::Product&>(
      ::GrpcApiPractice::_Product_default_instance_);
}
inline const ::GrpcApiPractice::Product& InvoiceDetails::product() const {
  // @@protoc_insertion_point(field_get:GrpcApiPractice.InvoiceDetails.product)
  return _internal_product();
}
inline void InvoiceDetails::unsafe_arena_set_allocated_product(
    ::GrpcApiPractice::Product* product) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.product_);
  }
  _impl_.product_ = product;
  if (product) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GrpcApiPractice.InvoiceDetails.product)
}
inline ::GrpcApiPractice::Product* InvoiceDetails::release_product() {
  
  ::GrpcApiPractice::Product* temp = _impl_.product_;
  _impl_.product_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GrpcApiPractice::Product* InvoiceDetails::unsafe_arena_release_product() {
  // @@protoc_insertion_point(field_release:GrpcApiPractice.InvoiceDetails.product)
  
  ::GrpcApiPractice::Product* temp = _impl_.product_;
  _impl_.product_ = nullptr;
  return temp;
}
inline ::GrpcApiPractice::Product* InvoiceDetails::_internal_mutable_product() {
  
  if (_impl_.product_ == nullptr) {
    auto* p = CreateMaybeMessage<::GrpcApiPractice::Product>(GetArenaForAllocation());
    _impl_.product_ = p;
  }
  return _impl_.product_;
}
inline ::GrpcApiPractice::Product* InvoiceDetails::mutable_product() {
  ::GrpcApiPractice::Product* _msg = _internal_mutable_product();
  // @@protoc_insertion_point(field_mutable:GrpcApiPractice.InvoiceDetails.product)
  return _msg;
}
inline void InvoiceDetails::set_allocated_product(::GrpcApiPractice::Product* product) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.product_);
  }
  if (product) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(product));
    if (message_arena != submessage_arena) {
      product = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, product, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.product_ = product;
  // @@protoc_insertion_point(field_set_allocated:GrpcApiPractice.InvoiceDetails.product)
}

// double deduction = 2;
inline void InvoiceDetails::clear_deduction() {
  _impl_.deduction_ = 0;
}
inline double InvoiceDetails::_internal_deduction() const {
  return _impl_.deduction_;
}
inline double InvoiceDetails::deduction() const {
  // @@protoc_insertion_point(field_get:GrpcApiPractice.InvoiceDetails.deduction)
  return _internal_deduction();
}
inline void InvoiceDetails::_internal_set_deduction(double value) {
  
  _impl_.deduction_ = value;
}
inline void InvoiceDetails::set_deduction(double value) {
  _internal_set_deduction(value);
  // @@protoc_insertion_point(field_set:GrpcApiPractice.InvoiceDetails.deduction)
}

// int64 quantity = 3;
inline void InvoiceDetails::clear_quantity() {
  _impl_.quantity_ = int64_t{0};
}
inline int64_t InvoiceDetails::_internal_quantity() const {
  return _impl_.quantity_;
}
inline int64_t InvoiceDetails::quantity() const {
  // @@protoc_insertion_point(field_get:GrpcApiPractice.InvoiceDetails.quantity)
  return _internal_quantity();
}
inline void InvoiceDetails::_internal_set_quantity(int64_t value) {
  
  _impl_.quantity_ = value;
}
inline void InvoiceDetails::set_quantity(int64_t value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:GrpcApiPractice.InvoiceDetails.quantity)
}

// int64 total = 4;
inline void InvoiceDetails::clear_total() {
  _impl_.total_ = int64_t{0};
}
inline int64_t InvoiceDetails::_internal_total() const {
  return _impl_.total_;
}
inline int64_t InvoiceDetails::total() const {
  // @@protoc_insertion_point(field_get:GrpcApiPractice.InvoiceDetails.total)
  return _internal_total();
}
inline void InvoiceDetails::_internal_set_total(int64_t value) {
  
  _impl_.total_ = value;
}
inline void InvoiceDetails::set_total(int64_t value) {
  _internal_set_total(value);
  // @@protoc_insertion_point(field_set:GrpcApiPractice.InvoiceDetails.total)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace GrpcApiPractice

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Models_2fInvoiceDetails_2eproto
