// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models/InvoiceDetails.proto

#include "Models/InvoiceDetails.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace GrpcApiPractice {
PROTOBUF_CONSTEXPR InvoiceDetails::InvoiceDetails(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.product_)*/nullptr
  , /*decltype(_impl_.deduction_)*/0
  , /*decltype(_impl_.quantity_)*/int64_t{0}
  , /*decltype(_impl_.total_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InvoiceDetailsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvoiceDetailsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvoiceDetailsDefaultTypeInternal() {}
  union {
    InvoiceDetails _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvoiceDetailsDefaultTypeInternal _InvoiceDetails_default_instance_;
}  // namespace GrpcApiPractice
static ::_pb::Metadata file_level_metadata_Models_2fInvoiceDetails_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Models_2fInvoiceDetails_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Models_2fInvoiceDetails_2eproto = nullptr;

const uint32_t TableStruct_Models_2fInvoiceDetails_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceDetails, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceDetails, _impl_.product_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceDetails, _impl_.deduction_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceDetails, _impl_.quantity_),
  PROTOBUF_FIELD_OFFSET(::GrpcApiPractice::InvoiceDetails, _impl_.total_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::GrpcApiPractice::InvoiceDetails)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::GrpcApiPractice::_InvoiceDetails_default_instance_._instance,
};

const char descriptor_table_protodef_Models_2fInvoiceDetails_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033Models/InvoiceDetails.proto\022\017GrpcApiPr"
  "actice\032\024Models/Product.proto\"o\n\016InvoiceD"
  "etails\022)\n\007product\030\001 \001(\0132\030.GrpcApiPractic"
  "e.Product\022\021\n\tdeduction\030\002 \001(\001\022\020\n\010quantity"
  "\030\003 \001(\003\022\r\n\005total\030\004 \001(\003b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Models_2fInvoiceDetails_2eproto_deps[1] = {
  &::descriptor_table_Models_2fProduct_2eproto,
};
static ::_pbi::once_flag descriptor_table_Models_2fInvoiceDetails_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Models_2fInvoiceDetails_2eproto = {
    false, false, 189, descriptor_table_protodef_Models_2fInvoiceDetails_2eproto,
    "Models/InvoiceDetails.proto",
    &descriptor_table_Models_2fInvoiceDetails_2eproto_once, descriptor_table_Models_2fInvoiceDetails_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_Models_2fInvoiceDetails_2eproto::offsets,
    file_level_metadata_Models_2fInvoiceDetails_2eproto, file_level_enum_descriptors_Models_2fInvoiceDetails_2eproto,
    file_level_service_descriptors_Models_2fInvoiceDetails_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Models_2fInvoiceDetails_2eproto_getter() {
  return &descriptor_table_Models_2fInvoiceDetails_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Models_2fInvoiceDetails_2eproto(&descriptor_table_Models_2fInvoiceDetails_2eproto);
namespace GrpcApiPractice {

// ===================================================================

class InvoiceDetails::_Internal {
 public:
  static const ::GrpcApiPractice::Product& product(const InvoiceDetails* msg);
};

const ::GrpcApiPractice::Product&
InvoiceDetails::_Internal::product(const InvoiceDetails* msg) {
  return *msg->_impl_.product_;
}
void InvoiceDetails::clear_product() {
  if (GetArenaForAllocation() == nullptr && _impl_.product_ != nullptr) {
    delete _impl_.product_;
  }
  _impl_.product_ = nullptr;
}
InvoiceDetails::InvoiceDetails(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcApiPractice.InvoiceDetails)
}
InvoiceDetails::InvoiceDetails(const InvoiceDetails& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InvoiceDetails* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.product_){nullptr}
    , decltype(_impl_.deduction_){}
    , decltype(_impl_.quantity_){}
    , decltype(_impl_.total_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_product()) {
    _this->_impl_.product_ = new ::GrpcApiPractice::Product(*from._impl_.product_);
  }
  ::memcpy(&_impl_.deduction_, &from._impl_.deduction_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.total_) -
    reinterpret_cast<char*>(&_impl_.deduction_)) + sizeof(_impl_.total_));
  // @@protoc_insertion_point(copy_constructor:GrpcApiPractice.InvoiceDetails)
}

inline void InvoiceDetails::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.product_){nullptr}
    , decltype(_impl_.deduction_){0}
    , decltype(_impl_.quantity_){int64_t{0}}
    , decltype(_impl_.total_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InvoiceDetails::~InvoiceDetails() {
  // @@protoc_insertion_point(destructor:GrpcApiPractice.InvoiceDetails)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InvoiceDetails::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.product_;
}

void InvoiceDetails::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InvoiceDetails::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcApiPractice.InvoiceDetails)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.product_ != nullptr) {
    delete _impl_.product_;
  }
  _impl_.product_ = nullptr;
  ::memset(&_impl_.deduction_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.total_) -
      reinterpret_cast<char*>(&_impl_.deduction_)) + sizeof(_impl_.total_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InvoiceDetails::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .GrpcApiPractice.Product product = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_product(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double deduction = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.deduction_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int64 quantity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.quantity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 total = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.total_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InvoiceDetails::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcApiPractice.InvoiceDetails)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .GrpcApiPractice.Product product = 1;
  if (this->_internal_has_product()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::product(this),
        _Internal::product(this).GetCachedSize(), target, stream);
  }

  // double deduction = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_deduction = this->_internal_deduction();
  uint64_t raw_deduction;
  memcpy(&raw_deduction, &tmp_deduction, sizeof(tmp_deduction));
  if (raw_deduction != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_deduction(), target);
  }

  // int64 quantity = 3;
  if (this->_internal_quantity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_quantity(), target);
  }

  // int64 total = 4;
  if (this->_internal_total() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_total(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcApiPractice.InvoiceDetails)
  return target;
}

size_t InvoiceDetails::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcApiPractice.InvoiceDetails)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .GrpcApiPractice.Product product = 1;
  if (this->_internal_has_product()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.product_);
  }

  // double deduction = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_deduction = this->_internal_deduction();
  uint64_t raw_deduction;
  memcpy(&raw_deduction, &tmp_deduction, sizeof(tmp_deduction));
  if (raw_deduction != 0) {
    total_size += 1 + 8;
  }

  // int64 quantity = 3;
  if (this->_internal_quantity() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_quantity());
  }

  // int64 total = 4;
  if (this->_internal_total() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_total());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InvoiceDetails::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InvoiceDetails::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InvoiceDetails::GetClassData() const { return &_class_data_; }


void InvoiceDetails::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InvoiceDetails*>(&to_msg);
  auto& from = static_cast<const InvoiceDetails&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcApiPractice.InvoiceDetails)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_product()) {
    _this->_internal_mutable_product()->::GrpcApiPractice::Product::MergeFrom(
        from._internal_product());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_deduction = from._internal_deduction();
  uint64_t raw_deduction;
  memcpy(&raw_deduction, &tmp_deduction, sizeof(tmp_deduction));
  if (raw_deduction != 0) {
    _this->_internal_set_deduction(from._internal_deduction());
  }
  if (from._internal_quantity() != 0) {
    _this->_internal_set_quantity(from._internal_quantity());
  }
  if (from._internal_total() != 0) {
    _this->_internal_set_total(from._internal_total());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InvoiceDetails::CopyFrom(const InvoiceDetails& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcApiPractice.InvoiceDetails)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InvoiceDetails::IsInitialized() const {
  return true;
}

void InvoiceDetails::InternalSwap(InvoiceDetails* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InvoiceDetails, _impl_.total_)
      + sizeof(InvoiceDetails::_impl_.total_)
      - PROTOBUF_FIELD_OFFSET(InvoiceDetails, _impl_.product_)>(
          reinterpret_cast<char*>(&_impl_.product_),
          reinterpret_cast<char*>(&other->_impl_.product_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InvoiceDetails::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Models_2fInvoiceDetails_2eproto_getter, &descriptor_table_Models_2fInvoiceDetails_2eproto_once,
      file_level_metadata_Models_2fInvoiceDetails_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace GrpcApiPractice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GrpcApiPractice::InvoiceDetails*
Arena::CreateMaybeMessage< ::GrpcApiPractice::InvoiceDetails >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcApiPractice::InvoiceDetails >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
