// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Models/ServiceStatus.proto

#include "Models/ServiceStatus.pb.h"
#include "Models/ServiceStatus.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace GrpcApiPractice {

} // namespace GrpcApiPractice

